# Generated by Django 4.0.4 on 2022-05-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LatestWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Latestwork/%m/%d', verbose_name='Фото')),
                ('title', models.CharField(max_length=20, verbose_name='Описание')),
            ],
        ),
    ]
