# Generated by Django 4.0.4 on 2022-06-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25, verbose_name='Имя')),
                ('lname', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('aboutme', models.TextField(verbose_name='О себе')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('W', 'Женщина')], max_length=3, verbose_name='Пол')),
                ('course', models.CharField(choices=[('first', '1'), ('second', '2'), ('third', '3'), ('fourth', '4'), ('fifth', '5')], default='1', max_length=8, verbose_name='Курс')),
                ('fee', models.CharField(choices=[('contract', 'Контракт'), ('grand', 'Бюджет')], max_length=8, verbose_name='Оплата')),
                ('is_active', models.BooleanField(verbose_name='Подтвержденный?')),
                ('university', models.CharField(help_text='Название', max_length=25, verbose_name='Университет')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
    ]
